// Shared write layer for the skill/agent graph. graph-data.json itself is
// fully REGENERATED by build-graph.py + scan-project-usage.py every time
// /skill-graph:build runs — it re-scans every configured source and every
// project under the scan roots from scratch and overwrites the file. Any edit
// made directly to that file would silently vanish on the next build.
//
// So edits (notes on a node, custom edges between two nodes) live in a
// separate file this module owns, and get merged onto a freshly-loaded
// graph-data.json at read time via applyOverlay(). Regeneration never
// touches this file, so nothing written here is ever lost to a re-scan.
//
// Required by both server/graph-query.js (Node/MCP) and app/src/main.js
// (Electron main process) — same CommonJS module, two different runtimes,
// one on-disk source of truth.
//
// The overlay file location is resolved per call rather than captured once at
// require time: it depends on which project is in scope, and a long-lived MCP
// server process outlives any single answer to that question.
const fs = require("fs");
const path = require("path");
const paths = require("./paths.js");

const EMPTY_OVERLAY = { notes: {}, customEdges: [], ratings: {}, importedRepos: [], importedNodes: [], categoryOverrides: {}, tags: {} };

// The calendar date where the person is, not where UTC is. `toISOString` is UTC,
// so east of Greenwich every evening write is stamped with yesterday — a note
// added at 00:50 in IST reads as the previous day, which makes the ordering of
// a day's notes wrong and looks like a bug in the tool rather than in the clock.
// Only the date is stored, so this is formatted from the local fields directly.
function today() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

function loadOverlay() {
  const OVERLAY_PATH = paths.overlayPath();
  if (!fs.existsSync(OVERLAY_PATH)) return { ...EMPTY_OVERLAY };
  try {
    const raw = JSON.parse(fs.readFileSync(OVERLAY_PATH, "utf-8"));
    return {
      notes: raw.notes || {}, customEdges: raw.customEdges || [], ratings: raw.ratings || {},
      importedRepos: raw.importedRepos || [], importedNodes: raw.importedNodes || [],
      categoryOverrides: raw.categoryOverrides || {}, tags: raw.tags || {},
    };
  } catch {
    // a corrupt overlay file must not take the whole graph down with it
    return { ...EMPTY_OVERLAY };
  }
}

function saveOverlay(overlay) {
  const OVERLAY_PATH = paths.overlayPath();
  fs.mkdirSync(path.dirname(OVERLAY_PATH), { recursive: true });
  fs.writeFileSync(OVERLAY_PATH, JSON.stringify(overlay, null, 2));
}

// Mutates `data` in place: adds imported nodes (skills/agents pulled from
// external repos via add_repo) to data.nodes FIRST, then attaches `notes`,
// `ratings` (+ a computed `avgRating`), and any `category` override to
// EVERY node including those, then appends custom edges (kind: "custom") to
// data.edges, skipping any whose endpoints no longer exist (a node could be
// renamed/removed by a later regen — a dangling custom edge must not crash
// the loader).
function applyOverlay(data) {
  const overlay = loadOverlay();
  data.nodes.push(...overlay.importedNodes);
  const byId = new Map(data.nodes.map((n) => [n.id, n]));
  data.nodes.forEach((n) => {
    n.notes = overlay.notes[n.id] || [];
    const ratings = overlay.ratings[n.id] || [];
    n.ratings = ratings;
    n.avgRating = ratings.length ? Math.round((ratings.reduce((s, r) => s + r.rating, 0) / ratings.length) * 10) / 10 : null;
    if (overlay.categoryOverrides[n.id]) n.category = overlay.categoryOverrides[n.id];
    n.tags = overlay.tags[n.id] || [];
  });
  overlay.customEdges.forEach((e, i) => {
    if (byId.has(e.from) && byId.has(e.to)) {
      data.edges.push({ from: e.from, to: e.to, weight: e.weight || 1, kind: "custom", label: e.label, overlayIndex: i });
    }
  });
  return data;
}

function addNote(nodeId, text) {
  const overlay = loadOverlay();
  if (!overlay.notes[nodeId]) overlay.notes[nodeId] = [];
  const note = { text, at: today() };
  overlay.notes[nodeId].push(note);
  saveOverlay(overlay);
  return { nodeId, index: overlay.notes[nodeId].length - 1, note };
}

function removeNote(nodeId, index) {
  const overlay = loadOverlay();
  const list = overlay.notes[nodeId] || [];
  if (index < 0 || index >= list.length) return { error: `no note at index ${index} for ${nodeId} (has ${list.length})` };
  const removed = list.splice(index, 1)[0];
  if (list.length === 0) delete overlay.notes[nodeId];
  saveOverlay(overlay);
  return { removed };
}

function addRating(nodeId, rating, note) {
  const r = Math.round(rating);
  if (r < 1 || r > 5) return { error: `rating must be 1-5, got ${rating}` };
  const overlay = loadOverlay();
  if (!overlay.ratings[nodeId]) overlay.ratings[nodeId] = [];
  const entry = { rating: r, note: note || "", at: today() };
  overlay.ratings[nodeId].push(entry);
  saveOverlay(overlay);
  const all = overlay.ratings[nodeId];
  const avg = Math.round((all.reduce((s, x) => s + x.rating, 0) / all.length) * 10) / 10;
  return { nodeId, index: all.length - 1, entry, avgRating: avg, ratingCount: all.length };
}

function removeRating(nodeId, index) {
  const overlay = loadOverlay();
  const list = overlay.ratings[nodeId] || [];
  if (index < 0 || index >= list.length) return { error: `no rating at index ${index} for ${nodeId} (has ${list.length})` };
  const removed = list.splice(index, 1)[0];
  if (list.length === 0) delete overlay.ratings[nodeId];
  saveOverlay(overlay);
  return { removed };
}

// Overrides a node's category regardless of source — a real catalog node's
// category comes from build-graph.py's crude keyword heuristic and gets
// reset on every regen; an imported node's category was guessed by the same
// heuristic at import time. Either way, the override here always wins
// (applied last in applyOverlay), and survives regen either way since it
// lives in the overlay, not graph-data.json.
function setCategory(nodeId, category) {
  const overlay = loadOverlay();
  overlay.categoryOverrides[nodeId] = category;
  saveOverlay(overlay);
  return { nodeId, category };
}

function removeCategoryOverride(nodeId) {
  const overlay = loadOverlay();
  if (!(nodeId in overlay.categoryOverrides)) return { error: `no category override for ${nodeId}` };
  const previous = overlay.categoryOverrides[nodeId];
  delete overlay.categoryOverrides[nodeId];
  saveOverlay(overlay);
  return { ok: true, previous };
}

// Tags are the fix for "category is too vague to reliably filter by": a
// node gets exactly one category but as many tags as actually apply (a
// skill can be both "react" and "security" and "testing" at once). Filtering
// by a combination of tags is how get_file_set narrows a broad catalog down
// to the actual correct set for a specific task.
function addTags(nodeId, tags) {
  const overlay = loadOverlay();
  if (!overlay.tags[nodeId]) overlay.tags[nodeId] = [];
  const existing = new Set(overlay.tags[nodeId]);
  tags.forEach((t) => existing.add(t.toLowerCase().trim()));
  overlay.tags[nodeId] = [...existing];
  saveOverlay(overlay);
  return { nodeId, tags: overlay.tags[nodeId] };
}

function removeTags(nodeId, tags) {
  const overlay = loadOverlay();
  const existing = overlay.tags[nodeId] || [];
  const toRemove = new Set(tags.map((t) => t.toLowerCase().trim()));
  overlay.tags[nodeId] = existing.filter((t) => !toRemove.has(t));
  if (overlay.tags[nodeId].length === 0) delete overlay.tags[nodeId];
  saveOverlay(overlay);
  return { nodeId, tags: overlay.tags[nodeId] || [] };
}

function addImportedRepo(repoMeta) {
  const overlay = loadOverlay();
  if (overlay.importedRepos.some((r) => r.label === repoMeta.label)) {
    return { error: `"${repoMeta.label}" is already imported — remove it first to re-import` };
  }
  overlay.importedRepos.push({ ...repoMeta, at: today() });
  saveOverlay(overlay);
  return { ok: true };
}

// Whether a label is currently registered. Distinguishes "imported" from
// "a clone left on disk by a remove_repo that did not delete it", which look
// identical on the filesystem and need opposite answers from add_repo.
function hasImportedRepo(label) {
  return loadOverlay().importedRepos.some((r) => r.label === label);
}

function addImportedNodes(nodes) {
  const overlay = loadOverlay();
  overlay.importedNodes.push(...nodes);
  saveOverlay(overlay);
  return { ok: true, count: nodes.length };
}

// Removes a repo's metadata AND every node it contributed (by sourceRepo
// label) — an imported repo and its nodes are one unit, never left half-removed.
function removeImportedRepo(label) {
  const overlay = loadOverlay();
  const repo = overlay.importedRepos.find((r) => r.label === label);
  if (!repo) return { error: `no imported repo labeled "${label}"` };
  overlay.importedRepos = overlay.importedRepos.filter((r) => r.label !== label);
  const before = overlay.importedNodes.length;
  overlay.importedNodes = overlay.importedNodes.filter((n) => n.sourceRepo !== label);
  const removedCount = before - overlay.importedNodes.length;
  saveOverlay(overlay);
  return { ok: true, repo, nodesRemoved: removedCount };
}

function addCustomEdge(from, to, label, weight) {
  const overlay = loadOverlay();
  const edge = { from, to, label: label || "related", weight: weight || 1, at: today() };
  overlay.customEdges.push(edge);
  saveOverlay(overlay);
  return { index: overlay.customEdges.length - 1, edge };
}

function removeCustomEdge(index) {
  const overlay = loadOverlay();
  if (index < 0 || index >= overlay.customEdges.length) return { error: `no custom edge at index ${index} (has ${overlay.customEdges.length})` };
  const removed = overlay.customEdges.splice(index, 1)[0];
  saveOverlay(overlay);
  return { removed };
}

module.exports = {
  overlayPath: paths.overlayPath, loadOverlay, saveOverlay, applyOverlay,
  addNote, removeNote, addRating, removeRating, addCustomEdge, removeCustomEdge,
  addImportedRepo, addImportedNodes, removeImportedRepo, hasImportedRepo,
  setCategory, removeCategoryOverride, addTags, removeTags,
};
